config/routes.rb
Rails.application.routes.draw do
  get 'recipe_foods/new'
  get 'recipe_foods/create'
  get 'recipe_foods/edit'
  get 'recipe_foods/update'
  get 'recipe_foods/destroy'
  get 'shopping_lists/index'
  devise_for :users
  root "users#index"
  resources :recipes, only: %i[index show new create edit update destroy] do
    resources :recipe_foods
    collection do
      get :public_recipes
    end
    member do
            patch 'toggle_public_status'
    end
    member do
      get 'generate_shopping_list'
    end
    patch 'update_public_status', on: :member
  end
  resources :users, only: %i[new create show edit update destroy]
  resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  resources :foods, only: %i[index show new create edit update destroy]
  resources :shopping_lists, only: :index
end

app/views/navbar/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Recipe App', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
         <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Public Recipes", public_recipes_recipes_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Foods", foods_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Recipes", recipes_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Shopping List", shopping_lists_index_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit profile", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      
    </div>
  </div>
</nav>