config/routes.rb
Rails.application.routes.draw do
  get 'recipe_foods/new'
  get 'recipe_foods/create'
  get 'recipe_foods/edit'
  get 'recipe_foods/update'
  get 'recipe_foods/destroy'
  get 'shopping_lists/index'
  devise_for :users
  root "users#index"
  resources :recipes, only: %i[index show new create edit update destroy] do
    resources :recipe_foods
    collection do
      get :public_recipes
    end
    member do
            patch 'toggle_public_status'
    end
    member do
      get 'generate_shopping_list'
    end
    patch 'update_public_status', on: :member
  end
  resources :users, only: %i[new create show edit update destroy]
  resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  resources :foods, only: %i[index show new create edit update destroy]
  resources :shopping_lists, only: :index
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods
  before_create :set_default_public_status
  scope :public_recipes, -> { where(public: true) }

  def toggle_public_status_and_visibility
    update(public: !public)

    if public
      add_to_public_category
    else
      remove_from_public_category
    end
  end

  private

  def set_default_public_status
    self.public ||= false
  end

  def add_to_public_category
    # Example: Add logic to associate the recipe with a public category
    # You might have a PublicCategory model and a join table
    # Modify the code based on your actual associations
    public_category.recipes << self if public_category
  end

  def remove_from_public_category
    # Example: Add logic to disassociate the recipe from the public category
    # You might have a PublicCategory model and a join table
    # Modify the code based on your actual associations
    public_category&.recipes&.delete(self)
  end

  def public_category
    # Example: Retrieve or create a PublicCategory based on your requirements
    # Modify the code based on your actual associations
    @public_category ||= PublicCategory.find_or_create_by(name: 'Public Recipes')
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  include ActionView::Helpers::NumberHelper

  before_action :set_recipe, only: %i[show edit update destroy generate_shopping_list]

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.includes(:foods).find(params[:id])
    @foods = @recipe.foods
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  def public_recipes
    @public_recipes = Recipe.includes(:user, :recipe_foods).where(public: true).order('created_at DESC')
  end

  def edit; end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'Recipe was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @recipe = current_user.recipes.find(params[:id])

    if @recipe.destroy
      redirect_to recipes_path, notice: 'Recipe deleted successfully'
    else
      redirect_to recipes_path, notice: 'Recipe cannot delete'
    end
  end

  def update_public_status
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: params[:public])
    render json: { status: 'success' }
  end

  def toggle_public_status
    @recipe = Recipe.find(params[:id])
    @recipe.toggle_public_status_and_visibility

    redirect_to @recipe, notice: 'Recipe public status updated successfully.'
  end

  def generate_shopping_list
    @foods = current_user.foods
    update_food_quantities
    filter_negative_quantities
    calculate_total
  rescue StandardError => e
    puts "DEBUG: An error occurred - #{e.message}"
    puts e.backtrace
  end

  private

  def update_food_quantities
    current_user.recipes.each do |recipe|
      update_food_quantity_for_recipe(recipe)
    end
  end

  def update_food_quantity_for_recipe(recipe)
    recipe.recipe_foods.includes(:food).each do |recipe_food|
      food = recipe_food.food
      test = @foods.find { |f| f.name == food.name }

      update_food_quantity(test, recipe_food) if test
    end
  end

  def update_food_quantity(food, recipe_food)
    food.quantity = [0, food.quantity - recipe_food.quantity].max
  end

  def filter_negative_quantities
    @foods.select! { |food| food.quantity.negative? }
    @foods.each { |food| food.quantity *= -1 }
  end

  def calculate_total
    @total = @foods.sum { |food| food.price * food.quantity }
  end

  def set_recipe
    @recipe = if params[:id] == 'public_recipes' || params[:id].nil?
                Recipe.public_recipes.where.not(user: current_user).find(params[:id])
              else
                current_user.recipes.find(params[:id])
              end
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'Recipe not found.'
    redirect_to recipes_path
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: @recipe, url: recipes_path, local: true) do |form| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, 'error') %> prohibited this recipe from being saved:</h2>

      <ul>
        <% @recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :preparation_time %>
    <%= form.text_field :preparation_time, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :cooking_time %>
    <%= form.text_field :cooking_time, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :public %>
    <%= form.check_box :public %>
  </div>

  <!-- Add similar fields for other attributes -->

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<div class="container">
  <h1>Edit Recipe</h1>

  <%= render 'form' %>

  <%= link_to 'Back', recipes_path %>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <h1>Recipes</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @recipes.each do |recipe| %>
        <tr>
          <td><%= link_to  recipe.name,recipe_path(recipe) %></td>
          <td><%= recipe.description %></td>
          <td><%= link_to 'Show', recipe %></td>
          <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
          <td>
            <% if recipe.user == current_user %>
              <%= button_to 'Remove', recipe, method: :delete, data: { confirm: 'Are you sure you want to delete this recipe?' } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Recipe', new_recipe_path %>
</div>

app/views/recipes/new.html.erb
<div class="container">
  <h1><%= action_name.capitalize %> Recipe</h1>

  <%= render 'form' %>

  <%= link_to 'Back', recipes_path %>
</div>

app/views/recipes/public_recipes.html.erb
<div class="container">
  <h1>Public Recipes</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Total Food Items</th>
        <th>Total Price</th>
        <th>User</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @public_recipes.each do |recipe| %>
        <tr>
          <td><%= recipe.name %></td>
          <td><%= recipe.foods.sum(:quantity) %></td>
          <td><%= number_to_currency(recipe.foods.sum(:price)) %></td>
          <td><%= recipe.user.name %></td>
          <td><%= link_to 'Show', recipe %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/recipes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1><%= @recipe.name %></h1>
      <p><strong>Preparation Time:</strong> <%= @recipe.preparation_time %></p>
      <p><strong>Cooking Time:</strong> <%= @recipe.cooking_time %></p>
      <p><strong>Description:</strong> <%= @recipe.description %></p>

      <div class="form-group">
        <%= form_with model: @recipe, local: true do |form| %>
          <%= form.check_box :public, { checked: @recipe.public, class: 'form-check-input', id: 'public-toggle' } %>
          <%= form.label :public, class: 'form-check-label', for: 'public-toggle' %>

          <%= button_to 'Toggle Public Recipe Status', toggle_public_status_recipe_path(@recipe), method: :patch, remote: true, form: { class: 'd-inline' }, class: 'btn btn-primary' %>
        <% end %>
      </div>

      <p><strong>User:</strong> <%= @recipe.user.name %></p>
    </div>

    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h2>Foods</h2>
        </div>

        <div class="card-body">
          <% if @recipe.foods.any? %>
            <table class="table">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Quantity</th>
                  <th>Value</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <% @recipe.recipe_foods.each do |recipe_food| %>
                  <tr>
                    <td><%= recipe_food.food.name %></td>
                    <td><%= recipe_food.quantity %></td>
                    <td>$ <%= recipe_food.food.price * recipe_food.quantity %></td>
                    <td>
                      <%= link_to 'Edit', edit_recipe_recipe_food_path(@recipe, recipe_food), class: 'btn btn-warning btn-sm' %> |
                      <%= button_to 'Destroy', recipe_recipe_food_path(@recipe, recipe_food), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% else %>
            <p>No foods added to this recipe.</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-md-8">
      <%= link_to 'Edit', edit_recipe_path(@recipe), class: 'btn btn-warning' %>
      <%= link_to 'Back', recipes_path, class: 'btn btn-secondary' %>
    </div>

    <div class="col-md-4 mt-2">
      <div class="card">
        <div class="card-header">
          <h2>Actions</h2>
        </div>

        <div class="card-body">
          <%= link_to 'Add Ingredient', new_recipe_recipe_food_path(recipe_id: (@recipe.nil? ? 'public_recipes' : @recipe.id)), class: 'btn btn-success btn-block mt-3' %>
          <%= link_to 'Generate Shopping List', shopping_lists_index_path(@recipe), class: 'btn btn-primary btn-block mt-3' %>
        </div>
      </div>
    </div>
  </div>
</div>