config/routes.rb
Rails.application.routes.draw do
  get 'recipe_foods/new'
  get 'recipe_foods/create'
  get 'recipe_foods/edit'
  get 'recipe_foods/update'
  get 'recipe_foods/destroy'
  get 'shopping_lists/index'
  devise_for :users
  root "users#index"
  resources :recipes, only: %i[index show new create edit update destroy] do
    resources :recipe_foods
    collection do
      get :public_recipes
    end
    member do
            patch 'toggle_public_status'
    end
    member do
      get 'generate_shopping_list'
    end
    patch 'update_public_status', on: :member
  end
  resources :users, only: %i[new create show edit update destroy]
  resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  resources :foods, only: %i[index show new create edit update destroy]
  resources :shopping_lists, only: :index
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  include ActionView::Helpers::NumberHelper

  before_action :set_food, only: %i[show edit update destroy]

  def index
    @foods = current_user.foods
  end

  def show; end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.new(food_params)
    if @food.save
      redirect_to foods_url, notice: 'Food item was successfully created.'
    else
      flash.now[:alert] = 'Food item could not be created.'
      render :new
    end
  end

  def edit; end

  def update
    if @food.update(food_params)
      redirect_to @food, notice: 'Food was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_url, notice: 'Food item was successfully deleted.'
  end

  private

  def set_food
    @food = Food.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_with(model: @food, local: true) do |form| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, 'error') %> prohibited this food from being saved:</h2>
      <ul>
        <% @food.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :measurement_unit %>
    <%= form.text_field :measurement_unit, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<div class="container">
  <h1 class="my-4">Edit Food</h1>

  <%= render 'form', food: @food %>

  <%= link_to 'Back', foods_path, class: 'btn btn-secondary' %>
</div>

app/views/foods/index.html.erb
<!-- app/views/foods/index.html.erb -->

<div class="container">
  <h1 class="my-4">Foods</h1>

  <table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Measurement Unit</th>
        <th>Unit Price</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.name %></td>
          <td><%= food.measurement_unit %></td>
          <td><%= number_to_currency(food.price) %></td>
          <td>
            <%= button_to 'Delete', food, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Add Food', new_food_path, class: 'btn btn-primary' %>
</div>

app/views/foods/new.html.erb
<div class="container">
  <h1 class="my-4">New Food</h1>

  <%= render 'form', food: @food %>

  <%= link_to 'Back', foods_path, class: 'btn btn-secondary' %>
</div>

app/views/foods/show.html.erb
<div class="container">
  <h1 class="my-4"><%= @food.name %></h1>

  <dl class="row">
    <dt class="col-sm-3">Name</dt>
    <dd class="col-sm-9"><%= @food.name %></dd>

    <dt class="col-sm-3">Measurement Unit</dt>
    <dd class="col-sm-9"><%= @food.measurement_unit %></dd>

    <dt class="col-sm-3">Unit Price</dt>
    <dd class="col-sm-9"><%= number_to_currency(@food.price) %></dd>
  </dl>

  <%= link_to 'Edit', edit_food_path(@food), class: 'btn btn-primary' %>
  <%= link_to 'Back', foods_path, class: 'btn btn-secondary' %>
</div>